DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;
DROP TABLE IF EXISTS couriers CASCADE;
DROP TABLE IF EXISTS orderItem CASCADE;
DROP TABLE IF EXISTS orderStatus CASCADE;
DROP TABLE IF EXISTS orderCourier CASCADE;