DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS addresses;
DROP TABLE IF EXISTS courier CASCADE;
DROP TABLE IF EXISTS orderItem;
DROP TABLE IF EXISTS orderStatus;
DROP TABLE IF EXISTS orderCouriers;